tap "reverbdotcom/reverb"
tap "versent/homebrew-taps"

cask "visual-studio-code"

brew "awscli"
brew "bash"
brew "bash-completion"
brew "curl"
brew "findutils"
brew "git"
brew "gnu-sed"
brew "go"
brew "icu4c"
brew "jq"
brew "libxml2"
brew "libxslt"
brew "macvim"
brew "mkcert"
brew "nginx"
brew "nodenv"
brew "nss"
brew "nvim"
brew "openssl"
brew "overmind"
brew "pipenv"
brew "postgres" # For CLI client tools like psql
brew "protobuf"
brew "protoc-gen-go"
brew "protopkg"
brew "pyenv"
brew "rbenv"
brew "readline"
brew "ruby-build"
brew "saml2aws"
brew "the_silver_searcher" # ag
brew "tilt-dev/tap/tilt"
brew "tilt-dev/tap/ctlptl"
brew "tmate"
brew "vcprompt"
brew "vim"
brew "wget"
